### ISSUE TITLE
Introduce Arcus.EventGrid.Testing with Hybrid Connections host

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#10]
Introduce `Arcus.EventGrid.Tests.Infrastructure` 📦  that contains our Hybrid Connections host to use in your integration tests.

### Tasks
- [x] Introduce new package
- [x] Provide documentation
- [x] Update README

**Comment by tomkerkhove** [comment]
Current documentation can be found here - https://github.com/arcus-azure/arcus.eventgrid/wiki/Running-integration-tests-with-Arcus

**Comment by tomkerkhove** [comment]
@SamVanhoutte @samneirinck

Seeking input for:
- Determining if we would want to add this package to `Arcus.EventGrid.All`, introduce `Arcus.EventGrid.Tests.All` or no metapackage.
- If you like the package name

**Comment by samneirinck** [comment]
I'd not expect test packages inside my live system. Personally, I prefer your second option, similar to the `Microsoft.AspNetCore.Mvc.Testing` package ([docs](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1)). No need to specify `.All` in my opinion, don't need as much granularity there.

**Comment by tomkerkhove** [comment]
That's indeed what I had in mind as well and I like the suggestion to remove `All` and use `Testing`.
I'm going to change that today.
