### ISSUE TITLE
`EventGridParser` only allows array of events

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#106]
**What feature would you like to have?**
In a previous discussion, I pointed out that the `EventGridParser` only allows a set of events to be parsed and not a single event. It was then discarded because the EventGrid resource will only send out array of events.

**Is your feature request related to a problem? Please describe.**
When implementating the [background job to receive CloudEvents](https://github.com/arcus-azure/arcus.webapi/issues/96) however, the event received is a single cloud event (not serialized as an array).

This results in a deserialization failure because we're trying to deserialize an array from a single entry.

**Additional context**
https://github.com/arcus-azure/arcus.webapi/issues/96

**Proposal**
Allow both single and many events be parsed by the `EventGridParser`.

**Comment by tomkerkhove** [comment]
Looks like this one is top prio

**Comment by stijnmoreels** [comment]
Yes and is fixed in open PR #112 .
