### ISSUE TITLE
Provide support for deserializing binary CloudEvents

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#109]
Provide support for deserializing binary CloudEvents.

These allow you to improve existing events by adding additional HTTP headers that provide the envelope information without breaking existing clients.

Example:
```http
POST /someresource HTTP/1.1
Host: webhook.example.com
ce-specversion: 1.0
ce-type: com.example.someevent
ce-time: 2018-04-05T03:56:24Z
ce-id: 1234-1234-1234
ce-source: /mycontext/subcontext
    .... further attributes ...
Content-Type: application/json; charset=utf-8
Content-Length: nnnn

{
    ... application data ...
}
```

Since we are using the official CloudEvents SDK, I hope, we should already support this but we should make sure this is the case.

See specification on [`3.1. Binary Content Mode
`](https://github.com/cloudevents/spec/blob/v1.0/http-protocol-binding.md#31-binary-content-mode) in CloudEvents spec.

**Comment by stijnmoreels** [comment]
[This line](https://github.com/arcus-azure/arcus.eventgrid/blob/e0daff69c2d56209e62275a13e662aafabfb31b5/src/Arcus.EventGrid/Parsers/EventParser.cs#L24) should prove that we can already do this, yes.
