### ISSUE TITLE
Improvement - Rename the `EventGridEventBatch<>` to `EventBatch<>`

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#113]
**What would you like to improve?**
The batch of events that will be returned from the `EventParser` will be called `EventGridEventBatch<>` while this is on fact just a batch of abstracted events.
A better name would be `EventBatch<>`.

**Comment by renebik** [comment]
@stijnmoreels: Is this something I can do?

**Comment by stijnmoreels** [comment]
> @stijnmoreels: Is this something I can do?

Yes, of course! I wanted to wait after #112 but you can already do it. I'll manage any merge conflicts.

Thanks for the help!
