### ISSUE TITLE
PublishRawAsync should allow you to choose between Event Grid & CloudEvents

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#117]
PublishRawAsync should allow you to choose between Event Grid & CloudEvents which is not the case today where it assumes Event Grid format.

> Flurl.Http: Call failed with status code 415 (The Content-Type header is either missing or it doesn't have a valid value. The content type header must either be application/cloudevents+json; charset=utf-8 or application/cloudevents-batch+json; charset=UTF-8.

**Comment by stijnmoreels** [comment]
It's also somewhat related to the issue I mentioned in #112 that the Event Grid event and CloudEvent is not isomorphic and that if we would remove all reference to the concrete event type, we would lose information and possible have corrupt events.

**Comment by tomkerkhove** [comment]
I don't see how these are related - You are publishing raw events here and as a publisher you'd want to have the choice on how to publish depending on your Event Grid topic.
