### ISSUE TITLE
Feature - CloudEvents v1.0 support, optionally even v0.2 & v0.3.

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#123]
**What feature would you like to have?**
We should support event parsing for CloudEvents v1.0, and optionally even v0.2 & v0.3.

Maybe the SDK can help here.

_Originally posted by @tomkerkhove in https://github.com/arcus-azure/arcus.eventgrid/pull/112_

**Comment by stijnmoreels** [comment]
Maybe we should provide a content type in the parser so we can be sure it's a cloud event.

**Comment by tomkerkhove** [comment]
I think it's best to provide a dedicated parser per spec version

**Comment by stijnmoreels** [comment]
> I think it's best to provide a dedicated parser per spec version

The SDK handles this for us. Already checks for several versions.
