### ISSUE TITLE
Update Azure resources to use the R&D subscription

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#127]
**What would you like to change?**
Currenltly, the Azure resources are used from my personal subscription. But they should exist on the R&D subscription.

Originally posted by @tomkerkhove :
>So what I'm seeing is that you have:
>
>One Service Bus namespace with 2 topics
>One Event Grid topic with Event Grid schema
>One Event Grid topic with CloudEvents schema
>If so, I'll add an issue to reflect this in our landscape

**Comment by tomkerkhove** [comment]
Re-opening as this is still pending.
