### ISSUE TITLE
Does our validation handshake support CloudEvents

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#138]
Does our validation handshake support CloudEvents format?

**Comment by tomkerkhove** [comment]
I think it does since we use an abstraction but want to verify this.

**Comment by stijnmoreels** [comment]
What do you refer to on 'validation handshake'?

**Comment by tomkerkhove** [comment]
This - https://eventgrid.arcus-azure.net/features/endpoint-validation

**Comment by stijnmoreels** [comment]
Hmm, not sure, haven't worked with that and not sure how it relates to CloudEvents. Not even sure if this is tested correctly?

**Comment by stijnmoreels** [comment]
Hmm, actually, the validation here is specific an Azure subscription validation model that is required, no CloudEvents. So no sure if this is something that can be done here.

**Comment by tomkerkhove** [comment]
Can we investigate if we cna support CloudEvents for this as well?

**Comment by stijnmoreels** [comment]
This seems like it can be done: https://docs.microsoft.com/en-us/azure/event-grid/cloudevents-schema#endpoint-validation-with-cloudevents-v10
https://github.com/cloudevents/spec/blob/v1.0/http-webhook.md#4-abuse-protection

But I don't think this includes the validation itself?

**Comment by tomkerkhove** [comment]
Nope, that just defines the spec - We'll need to see what the changes are for us to support this.

**Comment by stijnmoreels** [comment]
I think we can close since this was done in #182 , right?

**Comment by tomkerkhove** [comment]
Yes!
