### ISSUE TITLE
Evaluate if we should migrate to Microsoft.Azure.Management.EventGrid

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#140]
**What feature would you like to have?**
Evaluate if we should migrate to Microsoft.Azure.Management.EventGrid instead of our current SDK which is no longer updated for more than a year.

It looks like this new one contains new features as well so we should see what other things it enables us to do such as creating subscriptions, etc.

**Comment by stijnmoreels** [comment]
Hmm, not sure if the models we need are available in that library? Like the `EventGridEvent`?

**Comment by tomkerkhove** [comment]
Would be good to do an analysis of the differences and what the impact is, but low prio

**Comment by stijnmoreels** [comment]
Well, the Azure.Messaging.EventGrid package seems to be having all the deserialization logic for EventGrid and CloudEvent messages. https://github.com/Azure/azure-sdk-for-net/blob/473753f0d1c8a9c1cb4b11c19fad579b4786e849/sdk/eventgrid/Azure.Messaging.EventGrid/api/Azure.Messaging.EventGrid.netstandard2.0.cs#L16

**Comment by tomkerkhove** [comment]
So you are happy or concerned about that?

**Comment by stijnmoreels** [comment]
> So you are happy or concerned about that?

Created new issue with the benefits listed #193

**Comment by stijnmoreels** [comment]
Used the new Azure SDK for EventGrid instead in #193 .
