### ISSUE TITLE
Make event schemas more discoverable

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#15]
**Is your feature request related to a problem? Please describe.**
Currently our events schemas are called similar to `BlobEventData` which is not clear what exact event they represent.

**Describe the solution you'd like**
We should provide contracts that have names similar to the official event schemas such as `Microsoft.Storage.BlobCreated` would become `BlobCreatedEvent` instead of `BlobEventData`.

**Additional context**
Full list of our contracts and sample can be found in [docs](https://github.com/arcus-azure/arcus.eventgrid/wiki/Supported-Event-Contracts)

## Checklist
- [x] Implement feature
- [x] Update wiki
- [x] Ship 📦

**Comment by SeanFeldman** [comment]
👍 for fine grained event names.

Not sure I like the abstraction idea. `Microsoft.Storage.BlobCreated` is the event name. Why to add `BlobCreatedEvent` on top of that?

**Comment by tomkerkhove** [comment]
Are you saying you like "BlobCreated" more than "BlobCreatedEvent"?
________________________________

**Comment by SeanFeldman** [comment]
Yes. Just like I'm not a fan of " buttery butter", `AbcEvent` event is just `Abc`. You think in terms of  descriptions of what happened: MoneyDeposited, UserCreated. Not MoneyDepositedEvent or UserCreatedEvent 🙂

**Comment by tomkerkhove** [comment]
Initial thinking is that if I'm interested in the [`Microsoft.Devices.DeviceCreated`](https://docs.microsoft.com/en-us/azure/event-grid/event-schema-iot-hub) event that I can parse it as following:

```csharp
EventGridMessage<DeviceCreated> eventGridMessage = EventGridParser.Parse<DeviceCreated>(rawEvent);
```

Thoughts?

We've considered moving `DeviceCreated` to the `Microsoft.Devices.DeviceCreated` namespace but didn't do this as this can be confusing and want to be explicit that we own this schema. This is so that they blame us when it's not up to date or not - not Azure

**Comment by SamVanhoutte** [comment]
I would vote for EventGridMessage.Parse - as we are parsing a message, rather than an Event Grid.

**Comment by tomkerkhove** [comment]
@SamVanhoutte That's actually not correct as the payload will be a list that can [contain 1 or more events](https://docs.microsoft.com/en-us/azure/event-grid/event-schema) and from that perspective I don't think this makes sense - Both EventGridMessage as parsing on top of that.

Would it make sense to call it `EventsParser` of `EventGridEnvelopeParser` which output `EventGridEnvelope` which contains a list of events?

**Comment by SamVanhoutte** [comment]
true - good point.  I would avoid introducing envelope, however...
EventsParser can return a List of events?

**Comment by tomkerkhove** [comment]
Good feedback @SamVanhoutte  - Got it, will send a PR with a proposal this week!

**Comment by SeanFeldman** [comment]
Sidenote: it is so weird to see public discussions for private code 😉

**Comment by tomkerkhove** [comment]
Feature should be done and is awaiting review in #36
