### ISSUE TITLE
Provide opt-in to enable dependency tracking

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#156]
**What feature would you like to have?**
Provide opt-in to enable dependency tracking to measure performance during publishing of events.

Relates to https://github.com/tomkerkhove/k8s-event-grid-bridge/issues/182

**Comment by stijnmoreels** [comment]
We need a `ILogger` instance for that. What would be the best way to provide such an logger instance to the Azure Event Grid publisher? This publisher instance is created via a builder.

**Comment by tomkerkhove** [comment]
I would provide an overload where you can pass it. If non is passed, use NullLogger.
