### ISSUE TITLE
Move Azure Event Grid subscription validation to `Arcus.EventGrid.WebApi.Security` project

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#174]
**What feature would you like to have?**
We should have the Azure Event Grid subscription validation functionality available in the `Arcus.EventGrid.WebApi.Security` project.

**Comment by tomkerkhove** [comment]
Just curious - What's the reasoning in moving it into a dedicated package?

**Comment by stijnmoreels** [comment]
The project/package already exists. It now only contains the Event Grid authorization attribute that was reworked and moved from the `Arcus.EventGrid.Security` package/library. This old deprecated package also contains this subscription validation that wasn't moved yet.
