### ISSUE TITLE
Provide support to filter based on event payload for writing automated tests

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#178]
**What feature would you like to have?**
Provide support to filter based on event payload for writing automated tests instead of relying on the event ID.

**Comment by stijnmoreels** [comment]
Would this filter mean that you could filter on the typed CloudEvent/EventGridEvent payloads? Or only the event itself.
Maybe some context here could be helpful, where you could encountered the opportunity.

**Comment by tomkerkhove** [comment]
Now you can do the following:
```csharp
var rawReceivedEvent = _eventConsumerHost.GetReceivedEvent(eventId, timeout.Value);
```

But instead, I'd like to filter on one of the following things:
- Event type
- Information in the event's data field (raw and/or deserialized)
- Event subject

So giving us a func that gives us the `CloudEvent` and allows us to return `true` or `false`.

```csharp
var rawReceivedEvent = _eventConsumerHost.GetReceivedEvent(cloudEvent => cloudEvent.Subject.Contains("my-id"), timeout.Value);
```

But next to that I'd like to be able to have a func which gives me the deserialized data payload on which I can work.

```csharp
var rawReceivedEvent = _eventConsumerHost.GetReceivedEvent<OrderCreatedEvent>(orderCreatedEvent => orderCreatedEvent.OrderId == ("my-order-id"), timeout.Value);
```

**Comment by stijnmoreels** [comment]
Ok, that we can do! Maybe, in this case, you also want to get a set of events, as the filter could not always be referencing to a unique event?

**Comment by tomkerkhove** [comment]
For us it is aimed for single events at the moment, but who knows 🤷‍♂️

**Comment by stijnmoreels** [comment]
> For us it is aimed for single events at the moment, but who knows 🤷‍♂️

Aha, ok, bc you may get false positives when receiving on something that's available for multiple events.

**Comment by tomkerkhove** [comment]
That's certainly possible, but with great filtering power comes great responsibilities :D
