### ISSUE TITLE
Use WithExponentialRetry with EventGridPublisherBuilder

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.eventgrid#189]
**Description**
According to the documentation I should be able to use the WithExponentialRetry with the EventGridPublisherBuilder, see: https://eventgrid.arcus-azure.net/features/publishing-events/#resilient-publishing
![image](https://user-images.githubusercontent.com/32359437/134683475-010c2ff6-c24a-41ee-89b9-69fdc32d7d23.png)

However this does not seem to be implemented:
![image](https://user-images.githubusercontent.com/32359437/134683542-8f6fbfba-5a16-4d2a-b498-ea9e64e1677c.png)

I tried using both Arcus.EventGrid.All and Arcus.EventGrid.Publishing but unfortunately no luck. What am I doing wrong?

**Comment by tomkerkhove** [comment]
It should be available in the Arcus.EventGrid.Publishing namespace.

https://github.com/arcus-azure/arcus.eventgrid/search?l=C%23&q=WithExponentialRetry

**Comment by pim-simons** [comment]
Ah I understand from looking at the unittests, I had to use the interface IEventGridPublisherBuilderWithExponentialRetry like so
```
private IEventGridPublisherBuilderWithExponentialRetry CreateEventGridBuilder(string topicEndpoint, string endpointKey)
{
    return EventGridPublisherBuilder
        .ForTopic(topicEndpoint)
        .UsingAuthenticationKey(endpointKey);
}
```

And then refer to that, that wasn't immediately clear to me. But it's working now, thanks!

**Comment by stijnmoreels** [comment]
@pim-simons yeah, we tried to make a sort of 'guidee builder's where you would via intelisense be guided towards the next available option.
Something you see often in Microsoft-related frameworks too. Guess isn't as obvious as we thought. ☺️ A good lesson for us.

**Comment by pim-simons** [comment]
Let me take a look if I can change the documentation a little so that it's a bit clearer maybe, will create a PR for that

**Comment by stijnmoreels** [comment]
> Let me take a look if I can change the documentation a little so that it's a bit clearer maybe, will create a PR for that

Ok, great initiative! 👍 Thx

**Comment by pim-simons** [comment]
Well it looks like this was just an issue of the problem being between the chair and keyboard.
I took another look at it and honestly the documentation is fine, it was me not following it the right way (I was trying to place the `WithExponentialRetry` before `UsingAuthenticationKey` which was the issue. My bad 🤦🏻‍♂️
