### ISSUE TITLE
Remove dependency on netfx-Guard and use Guard.NET instead

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#20]
**Describe the solution you'd like**
Remove dependency on `netfx-Guard` which is outdated and use `Guard.NET` instead.

**Additional context**
This is only the case for `Arcus.EventGrid.Publishing`

**Comment by murdockcrc** [comment]
If no one else volunteers, assign this one to me plz. 
Would like to get my hands dirty with the Arcus initiative.

**Comment by tomkerkhove** [comment]
This is already done.
