### ISSUE TITLE
Suggestion - Azure Event Grid container image

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#23]
**What feature would you like to have?**
Container image which allows you to use HTTP to send events to a custom Azure Event Grid topic.

**Is your feature request related to a problem? Please describe.**
No, but it would simplify pushing custom events to Event Grid in applications by delegating the tech details for grid to our container and use it as a sidecar.

**Describe the solution you'd like**
Container should be easily deployable and have following environment variables:
- Custom topic to push to
- Authentication key for custom topic

Events should be sent by calling the service via HTTP POST.

**Describe alternatives you've considered**
Not include this in Arcus and use this as a spin-off.

**Additional context**
Schema of request to be defined later on.

**Comment by tomkerkhove** [comment]
I'm including :
- @SamVanhoutte to see if he finds this suitable for Arcus or should be done elsewhere
- @samneirinck to see if this makes sense

**Comment by SamVanhoutte** [comment]
If this means adding the container code to the repo, that would be great.  It probably also means we'd have to set up a docker repo on dockerhub for arcus.  I definitely see value in that

**Comment by tomkerkhove** [comment]
Given this will have it's own backlog, versioning and lifecycle I would suggest to create a dedicated repo for it such as arcus-azure/arcus.eventgrid.sidecar

**Comment by samneirinck** [comment]
I can see the value, not sure many people will use it, but if it's out there, why not.

We need to make sure it has enough automation to automatically publish new tags whenever the library updates though, otherwise I fear it will not get updated (to the latest versions) in the long run.

**Comment by samneirinck** [comment]
I guess it's easiest in a dedicated repo (since it will actually need to consume published packages, and not the source), I only fear about its discoverability.

**Comment by tomkerkhove** [comment]
That's correct so let's move this to `arcus-azure/azure-event-grid-sidecar`.

In terms of discoverability, we can arrange that and introduce an "Installation"-page to this documentation with a pointer to the container documentation.

**Comment by tomkerkhove** [comment]
We're going to do this as part of https://github.com/arcus-azure/arcus.eventgrid.sidecar.
Closing this issue.
