### ISSUE TITLE
Provide capability to pass uri & validate topic endpoint

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#24]
Now the topic endpoint for the `EventGridPublisher` is stored as a primitive `string` meaning that we have to verify every time we use it if it's a correct endpoint.

We could possibly store it as a `Uri` and verify if we indeed have a http endpoint (maybe even wrap it in its own domain model). 
This would reduce the now 4 validation checks into 1 and would make the overall usage of the endpoint more safe to use.

The builder don't have to be changed for this, only an internal change.

Just a proposal.

**Comment by tomkerkhove** [comment]
Maybe it would make more sense to take in a `Uri` for the topic endpoint so that it's the consumer his responsibility?

**Comment by SamVanhoutte** [comment]
Agree a Uri would be great.  Do you see this as an overload (and making the string one Obsolete)?

**Comment by tomkerkhove** [comment]
I personally would prefer that route indeed

**Comment by tomkerkhove** [comment]
Considering this as specs defined!

### Task list
- [ ] Introduce overload where Uri is passed and validated
- [ ] Validate existing approach by passing string to Uri
