### ISSUE TITLE
Use new Azure SDK clients for Azure EventGrid publishing

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#243]
**Is your feature request related to a problem? Please describe.**
Currently, we use a dedicated `IEventGridPublisher` interface to publish evens (raw, `CloudEvent`, `EventGridEvent`) to an Azure EventGrid resource.
Since the Azure SDK is moving towards a [system where clients are registered in the application](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.extensions.azure-readme-pre), we should also move towards that directions. We already did some work on adding correlation dependency tracking on the `ServiceBusSender`, which can also be injected via this system, but since we use a dedicated publisher for EventGrid, we can't use this new Azure SDK client registration system, yet.

**Describe the solution you'd like**
Provide a custom implementation of the `EventGridPublisherClient` that tracks the EventGrid dependency and enriches the event with the operation parent ID and transaction ID.
The consumer should be able to override the way these properties are added to the event, as they should be defined as [custom delivery properties](https://docs.microsoft.com/en-us/azure/event-grid/delivery-properties) in Azure EventGrid. 
The options provided should inherit from the `EventGridPublisherClientOptions` and make sure that we can configure the property names for the correlation information and the resilient functionality (exceptional back-off, circuit-breaker) which are now available in our custom EventGrid publisher.

**Comment by stijnmoreels** [comment]
But, seems like if we want to add custom properties, we have to add this to the custom delivery properties in the event subscription: https://docs.microsoft.com/en-us/azure/event-grid/delivery-properties

**Comment by pim-simons** [comment]
I find it a bit hard to offer some good feedback on this since I haven't used this a lot, but from your description and pseudo code it seems like a good idea.
