### ISSUE TITLE
Deprecate `Arcus.EventGrid` and `Arcus.EventGrid.Publishing`

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#248]
**Is your feature request related to a problem? Please describe.**
We should use Microsoft's new Azure SDK for EventGrid operations, so we have created a new library called `Arcus.EventGrid.Core` for this. The other libraries should be made deprecated as the parsing functionality is already available in the Azure SDK.

**Describe the solution you'd like**
Determine which libraries could be made deprecated. This seems like the `Arcus.EventGrid` and `Arcus.EventGrid.Publishing` but have to check.

**Comment by stijnmoreels** [comment]
The `Arcus.EventGrid` made sure that we can easily handle events without the type (cloud or event grid events), but the Azure SDK now supports a new set of methods `CloudEvent.Parse` and `EventGridEvent.Parse` and also for many events, which made me wonder if this package has any added value now, as it doesn't support these new types but is still supporting the older SDK types. So, not sure if it would be worth effort to change this library.

The `Arcus.EventGrid.Publishing` library has been changed with the `Arcus.EventGrid.Core` library that includes publishing using the new Azure SDK.

Both packages can be made deprecated on NuGet, right? Once, we release the `Arcus.EventGrid.Core` package, of course.
@fgheysels ?

**Comment by fgheysels** [comment]
We should a have a short meeting on this @stijnmoreels

**Comment by stijnmoreels** [comment]
We should first verify that the expired client secret background job can use the new `Arcus.EventGrid.Core` package before deprecating these two.
https://github.com/arcus-azure/arcus.backgroundjobs

**Comment by stijnmoreels** [comment]
Both packages are now set on deprecated in NuGet:
https://www.nuget.org/packages/Arcus.EventGrid
https://www.nuget.org/packages/Arcus.EventGrid.Publishing

And we have successfully made the additions to BackgroundJobs. We can now safely remove these two projects from the solution.

**Comment by stijnmoreels** [comment]
Closing this one, will be handled further in #280 and #281.
