### ISSUE TITLE
Provide support for official schemas in favor of our own

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#46]
Last week [Microsoft released a blog post](https://azure.microsoft.com/en-us/blog/deliver-the-right-events-to-the-right-places-with-event-domains/) with update on Azure Event Grid which announced an updated Azure SDK:

> **We have updated the .Net, Java, and Go SDKs to make consuming Azure Native Events even easier. Using the latest release of each, the SDK is now aware of all available event types being published by Azure.** This means you can use Event Grid’s eventGridSubscriber to deserialize events directly for all known event types and start writing code against the content of the event rather than first having to deal with manually deserializing JSON into various different event type classes. Check the different SDKs for an easier experience managing your Event Grid resources and events.

After digging I found them [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventgrid.models?view=azure-dotnet)

Question is, should we still provide support for the Azure schemas over the official ones or should we use the official ones and make them compatible with our approach?

I would suggest to invest our time in the latter so that we can focus on other features as it will be hard to keep up.

## Checklist
- [ ] Align with new SDK
- [ ] Update documentation
- [ ] Remove our custom types & interface

**Comment by tomkerkhove** [comment]
Any thoughts @samneirinck 	@SamVanhoutte 	@stijnmoreels 	?

**Comment by samneirinck** [comment]
Don't think it makes sense to keep the ones in Arcus. What impact does it have?

**Comment by stijnmoreels** [comment]
I'll have to look closer both in the blog post and the update to give you a good awnser. It seems logic to follow the Azure schema changes like @samneirinck said?

**Comment by tomkerkhove** [comment]
That's what I would suggest as well. Briefly discusses with @SamVanhoutte 	this week and we would suggest that we make our approach compatible with the official approach.

Let me know what you think and I'll create a dedicated story for this.

**Comment by SamVanhoutte** [comment]
Agree - no reason to maintain our own. Will this introduce a breaking change, introducing this?

**Comment by tomkerkhove** [comment]
We would have to look into it but I think so. Schemas can be marked as obsolete but it's going to be the core that has to be changed again to support them.

**Comment by tomkerkhove** [comment]
@stijnmoreels This issue was closed but we still have all the legacy schemas in there or am I wrong?

![image](https://user-images.githubusercontent.com/4345663/65704579-13dd7c80-e087-11e9-8d01-cdc860046fcf.png)

**Comment by stijnmoreels** [comment]
> @stijnmoreels This issue was closed but we still have all the legacy schemas in there or am I wrong?
> 
> ![image](https://user-images.githubusercontent.com/4345663/65704579-13dd7c80-e087-11e9-8d01-cdc860046fcf.png)

No, that's correct. We still have some obsolete schemas aside from the new way of creating events. Both are still supported by the parser and other functionality until further notice.

**Comment by tomkerkhove** [comment]
Hm is there a reason why we still support this as I thought I've mentioned you shouldn't care about those given we're going for a new major version anyway :D

**Comment by stijnmoreels** [comment]
> Hm is there a reason why we still support this as I thought I've mentioned you shouldn't care about those given we're going for a new major version anyway :D

Yeah, but probably was for another PR.

**Comment by tomkerkhove** [comment]
Can we carve that out please so that we no longer have it with us?
