### ISSUE TITLE
Provide capability to push a raw event

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#57]
As of today, we only support pushing events with a typed schema.

We should also provide the capability to push events without a schema based on a raw JSON string.

## Syntax Proposal
```csharp
string licensePlate = "1-TOM-337";
string eventSubject = $"/cars/{licensePlate}";
string eventId = Guid.NewGuid().ToString();
string rawEventPayload = $"{{ \"licensePlate\": \"{licensePlate}\"}}";

await eventGridPublisher.Publish(eventId, eventSubject, rawEventPayload);
```

## Task List
- [X] Implementation
- [ ] Documentation

**Comment by stijnmoreels** [comment]
Maybe create a dedicated type for this (like `RawEvent...` or something) instead of passing all arguments separately while they all relate to the same value/event.

Also, we should check on this raw string to have valid JSON. If we agree on a separate type, this could be done inside the type.

**Comment by stijnmoreels** [comment]
> Maybe create a dedicated type for this (like `RawEvent...` or something) instead of passing all arguments separately while they all relate to the same value/event.

But this is maybe something for another issue

**Comment by tomkerkhove** [comment]
We should make it super simple for consumers to use it so the approach should be along the lines of the proposal.

However, it could use a `RawEvent` internally that complies with our approach indeed - That's a good suggestion. But it should not leak to the consumer as it makes it over-complicated.

The raw JSON should be validated in the sense that it should be a valid JSON payload but we should not enforce anything as it should be used for the event data payload which is always different per customer/scenario/etc.

I don't know if there is a way to validate these but the sample above would work as well.

**Comment by tomkerkhove** [comment]
I'll pick this up later this week/next week

**Comment by tomkerkhove** [comment]
In terms of validation - [JSON.Net Schema](https://www.newtonsoft.com/jsonschema) supports this but is not free.

We'll use the approach suggested by @stijnmoreels 	for now.

**Comment by stijnmoreels** [comment]
Or using the F# JSON Type Provider which both can validate JSON based on a schema and based on a sample file. 😉

**Comment by stijnmoreels** [comment]
> I'll pick this up later this week/next week

😓 I've already used my 4h on Arcus this month. Have to wait till Feb.

**Comment by tomkerkhove** [comment]
> Or using the F# JSON Type Provider which both can validate JSON based on a schema and based on a sample file. And allows strong typing dynamically at runtime. 😉
> 
> Hooray for F#🎉

Will provide a basic approach for first version of this feature, feel free to PR something if you want.

**Comment by tomkerkhove** [comment]
Reopening as docs are not there yet
