### ISSUE TITLE
Improve deserialization of custom events for DataVersion & EventType

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#66]
Improve deserialization of custom events for DataVersion & EventType are always populated.

**Current Situation**
Current situation you always need to provide a constructor given the setter is private:

```csharp
public class RawEvent : Event<object>
{
	public RawEvent(string id, string type, string body, string subject, string dataVersion, DateTimeOffset eventTime)
	{
		Guard.NotNullOrWhitespace(id, nameof(id), "No event id was specified");
		Guard.NotNullOrWhitespace(type, nameof(type), "No event type was specified");
		Guard.NotNullOrWhitespace(body, nameof(body), "No event body was specified");
		Guard.NotNullOrWhitespace(dataVersion, nameof(dataVersion), "No data version body was specified");
		Guard.For<ArgumentException>(() => body.IsValidJson() == false, "The event body is not a valid JSON payload");

		var parsedBody = JToken.Parse(body);

		DataVersion = dataVersion;
		Subject = subject;
		EventType = type;
		Id = id;
		Data = parsedBody;
		EventTime = eventTime;
	}

	public RawEvent()
	{
	}

	[JsonConstructor]
	protected RawEvent(string dataVersion, string eventType)
	{
		DataVersion = dataVersion;
		EventType = eventType;
	}

	public override string DataVersion { get; }
	public override string EventType { get; }
}
```

**Proposal**
None, but this should be improved to avoid misdeserialization.

**Comment by tomkerkhove** [comment]
Maybe this is something for you @stijnmoreels 	but don't feel obliged to pick it up.

One thing we could do is give the property a setter but not sure if we should given this tends to be fixed. Maybe this situation is exceptional.

**Comment by stijnmoreels** [comment]
So the problem is that we have to define a JSON ctor for those two properties and we should look into if that could be avoided?

Second, why do we have an empty ctor?

**Comment by tomkerkhove** [comment]
Empty ctor is enforced by Event but will probably go away when we integrate with official Azure schemas (#46)

**Comment by tomkerkhove** [comment]
> So the problem is that we have to define a JSON ctor for those two properties and we should look into if that could be avoided?

Yes, without just providing the setting which is accessible to everyone unless we are fine with that. However, I'm not sure if we should do that..

**Comment by stijnmoreels** [comment]
Has the code open, but don't quite fully understand the problem and to what solution you would want to evolve. Could you elaborate a little bit more?

**Comment by tomkerkhove** [comment]
The problem is that we've had to introduce the following constructor:
```csharp
[JsonConstructor]
protected RawEvent(string dataVersion, string eventType)
{
	DataVersion = dataVersion;
	EventType = eventType;
}
```

This is because deserialization wasn't working correctly given we only have a default ctor (enforced) and the other one.

However, reading this issue again now I'm not sure if using the contructor mentioned above is that big of an issue. Thoughts?

**Comment by stijnmoreels** [comment]
> However, reading this issue again now I'm not sure if using the contructor mentioned above is that big of an issue. Thoughts?

Yes, especially if you say that the default empty ctor will be removed; I don't see that much of an issue.
We can enforce this ctor (dataVersion and eventType) via the `Event` parent?

**Comment by tomkerkhove** [comment]
I think this was due to serialization but it has json constructor attribute on the other one.

Can't fully recall but feel free to have a look and PR a fix if it still works.

**Comment by fgheysels** [comment]
I'm having a look at it.
I wonder why `Id` is not a mandatory property ?  shouldn't each event have an id ?

**Comment by tomkerkhove** [comment]
Thanks!

> I wonder why `Id` is not a mandatory property ? shouldn't each event have an id ?

No, if it's not specified it will be automatically generated.

> I also do find it strange, that `Event` has a constructor which takes an Id argument and another constructor that has an `Id` and `Subject` argument.
> As I read it, this would mean to me that subject is not mandatory, since I can instantiate an `Event` without a `Subject`. However, if I would try to instantiate an `Event` using the 2-arg ctor, and I pass in 'null' or an empty string as `Subject`, an exception is being thrown.
> This means that I cannot do any constructor chaining like this:
> 
> ```cs
> public class Event
> {
>      protected Event( string id ) : this(id, null) {}
> 
>      protected Event(string id, string subject) {}
> }
> ```
> 
> since in the 2-arg ctor, the 'subject' argument is being checked and an exception is thrown when subject is null or whitespace.
> If `Subject` is not mandatory, I'd suggest to remove the Guard clause on ` Subject`.

That actually sounds like a bug, `subject` should be optional indeed.
Thanks for fixing this!

**Comment by stijnmoreels** [comment]
Current situation is updated:

```csharp
public class CarEventData
{
    public CarEventData(string licensePlate)
    {
        LicensePlate = licensePlate;
    }

    public string LicensePlate { get; }
}

public class NewCarRegistered : EventGridEvent<CarEventData>
{
    private const string DefaultDataVersion = "1",
                                    DefaultEventType = "Arcus.Samples.Cars.NewCarRegistered";

    // `JsonConstructor` attribute is not necesary but can help as documentation for the event.
    [JsonConstructor]
    private NewCarRegistered() { }

    public NewCarRegistered(string id, string subject, string licensePlate)
        : base(id, subject, new CarEventData(licensePlate), DefaultDataVersion, DefaultEventType) { }
}
```

No override properties for `DataVersion` and `EventType` is needed anymore since everything is passed allong in the ctor.

**Comment by tomkerkhove** [comment]
❤️, thanks!
