### ISSUE TITLE
Suffix all async methods with "Async"

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#72]
We should suffix all async methods with "Async" so that it's clear for consumers that it's an asynchronous method that needs to be awaited.

All current operations should be kept around and deprecated while new operations are being added:
```csharp
[Obsolete("Use DoSomethingAsync instead")]
public async Task DoSomething() {}

public async Task DoSomethingAsync() {}
```

Relates to https://github.com/arcus-azure/arcus/issues/28.

**Comment by stijnmoreels** [comment]
I'm wondering, have we already published the next patch/minor/major version of this repo? If not, we could just rename the interface methods (on the `IEventGridPublisher.PublishRaw` for instance, since this is new?).

**Comment by tomkerkhove** [comment]
Yes, rename here is ok

**Comment by tomkerkhove** [comment]
Re-opening as our testing tools aren't suffixed yet

**Comment by stijnmoreels** [comment]
You mean the hybrid consumer host?
I think I wasn't sure if you would like to update obsolete types.

**Comment by tomkerkhove** [comment]
All our hosts actually, we have one for service bus as well.

Tom Kerkhove
Azure Architect at Codit, Microsoft Azure MVP

________________________________
