### ISSUE TITLE
Provide capability to push many raw events

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#74]
**What feature would you like to have?**
We support now the capability to push a single raw event with the `EventGridPublisher.PublishRaw`, but since the typed variant `.Publish` also has a `.PublishMany` capability; it seems reasonable to also have this in the context of raw events.

## Proposal
```csharp
var rawEvents = new []
{
    new RawEvent("id", "type", "body", "subject", "dataversion", DateTimeOffset.Now)
};
eventGridPublisher.PublishMany(rawEvents)
```

**Describe alternatives you've considered**
Because a raw event consists of multiple input values (and not just a typed instance); it seems reasonable to allow a series of the `RawEvent` (already in repo) to become part of the signature.

**Comment by tomkerkhove** [comment]
@stijnmoreels 	Can you update the docs as well please?
