### ISSUE TITLE
Provide support for Cloud Events

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.eventgrid#8]
Provide support for sending and handling Cloud Events according to the [CNCF spec](https://github.com/cloudevents/spec/blob/master/spec.md).

- [CloudEvents support in Azure Event Grid docs](https://docs.microsoft.com/en-us/azure/event-grid/cloudevents-schema)
- [CloudEvents v0.1 Schema](https://docs.microsoft.com/en-us/azure/event-grid/cloudevents-schema#cloudevent-schema)

**Comment by stijnmoreels** [comment]
This is still on v0.1, but since it's an open standard it would be in my opinion a definite required feature for the project.

**Comment by stijnmoreels** [comment]
Would this mean that we would have besides the `IEvent` contract, a `ICloudEvent` contract with the values of the standard. And that the Event publishing and parsing mechanism should support both?

Maybe a parent interface can be created acting as a _Tag Interface_ for this.

**Comment by tomkerkhove** [comment]
Cloud Events are actually "already" in v0.2 and I've updated the issue.

A `ICloudEvent` would be good, but it should be versioned somehow where the namespace is first thing that comes to mind, but not ideal I think.

Would it make sense if we provide different Event Grid publishers based on spec that they want to use? I think it does.

We should support both publishing & parsing cloud events, but we can seperate that in seperate PRs/issues if we want. It's decoupled as pushing in Cloud Events does not mean you have to receive in that format.

If you mean a "Marker Interface" with a "Tag Interface" I would discourage that - https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/interface

**Comment by stijnmoreels** [comment]
> If you mean a "Marker Interface" with a "Tag Interface" I would discourage that - https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/interface

Yeah, I know. It's sometimes weird that the design guidelines for C# **discourage** this while in F# the same (kind of) is **encourged** with Discriminated Unions.

**Comment by stijnmoreels** [comment]
When updating the test infrastructure in Azure, the following changes has to be made to the ARM template:
* Add subscription to the Event Grid with a CloudEvent schema
* Add EventGrid topic so LogicApps can receive messages
* Add (Copy from existing) LogcApps without any request schema so  future CloudEvent schema's are also supported

**Comment by stijnmoreels** [comment]
The initial cloud support could be considered done I think.

**Comment by tomkerkhove** [comment]
Actually not yet I think - Can you provide some documentation on this feature please?

**Comment by stijnmoreels** [comment]
> Actually not yet I think - Can you provide some documentation on this feature please?

Ah, let me check.

**Comment by tomkerkhove** [comment]
Docs are available on https://eventgrid.arcus-azure.net/features/deserializing-events
