### ISSUE TITLE
Q: EventGridParser.Parse missconception

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.eventgrid#90]
**Description**
The `EventGridParser` parses multiple raw events into a typed batch model But I'm not sure if the name `Parse` is entirely a correct name for this.
If we want to parse a single raw event, then the parser fails and that (again) is not something I would consider a valid response since the `EventGridParser` CAN in fact parse a single event.

> The parser fails with an Newtonsoft.Json specific exception when loading the raw JSON into the `JArray.Parse` function.

**Comment by tomkerkhove** [comment]
We have to align with how Event Grid works and there they will always give you a list of events. In that case I think the current approach makes sense, no?

Or am I misinterpreting your question wrong?

**Comment by stijnmoreels** [comment]
Ah, OK. So when you use this parser; the input will always be a list because event grid works like this?
In that case, I'll close this issue.

**Comment by tomkerkhove** [comment]
That is correct! Azure Event Grid will always give you a list of events, even if only one event is being pushed.

If that is ok for you, I'd keep it as is indeed.
